apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: abbadanmusa/smart-proctor-auth
          resources:
            limits:
              cpu: "200m"
              memory: "128Mi"
            requests:
              cpu: "200m"
              memory: "128Mi"
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: auth-mongo-secret
                  key: MONGO_URI
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: JWT_SECRET
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: 'smart-proctor-nats'
            - name: CORS_ALLOWED_ORIGINS
              value: 'http://localhost:5173,https://smartproctor.dev,https://www.smartproctor.dev,https://494a9d6e096e.ngrok-free.app'
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  type: ClusterIP
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000
